version: '3'
services:
  product-service:
    build: .
    volumes:
      - './usr/src/app'
    ports:
      - '5002:80'
  website:
    image: 'php:apache'
    volumes:
      - './website:/var/www/html'
    ports:
      - '5020:80'
